### ISSUE TITLE
http says no.

### ISSUE THREAD

**Issue by mattstein** [jasonmccallister/mccallister.dev#2]
I'm enamored with this Bref+Yii+Lambda business you've got going on here, but sadly it looks like visitors on port 80 aren't invited to the party. 😢 

```
➜ curl http://mccallister.dev
curl: (7) Failed to connect to mccallister.dev port 80: Connection refused
```

**Comment by jasonmccallister** [comment]
@mattstein that is a good point, one of those downsides of API Gateway is no HTTP. Bref talks about it in more detail here: https://bref.sh/docs/websites.html

> The main downside is that API Gateway only supports HTTPS. Hosting websites on HTTPS is a good thing, however that means that there is no redirection from HTTP to HTTPS. In short, https://website.com will work but not http://website.com. It is up to you to decide if this limitation is acceptable for your use case.

This did give me a little pause... but seeing how `.dev` TLDs require HTTPS I went with it.

**Comment by mattstein** [comment]
Fair enough, @jasonmccallister. I pointed this out in case you didn't already know, but clearly you did!
